# Generated by Django 4.0.2 on 2022-04-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlibrary',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='courses', to='products.Course'),
        ),
        migrations.AddField(
            model_name='userlibrary',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
