# Generated by Django 4.0.2 on 2022-04-16 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userlibrary_courses_userlibrary_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlibrary',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='userlibrary',
            name='products',
        ),
    ]
