# Generated by Django 4.0.2 on 2022-03-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_course_pricing_tier'),
        ('users', '0006_userlibrary'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlibrary',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='courses', to='products.Course'),
        ),
    ]
