# Generated by Django 4.0.2 on 2022-03-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='plan_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='flw_subscription_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
