# Generated by Django 4.0.2 on 2022-04-16 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=230)),
                ('product_type', models.CharField(choices=[('digital', 'Digital Product'), ('ticket', 'Ticket'), ('service', 'Service'), ('subscription', 'Subscription')], max_length=15)),
                ('description', models.TextField()),
                ('content', models.FileField(blank=True, null=True, upload_to='')),
                ('content_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
                ('currency', models.CharField(max_length=4)),
                ('original_price', models.IntegerField(blank=True, default=0, null=True)),
                ('preoder_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('preview_video', models.FileField(blank=True, null=True, upload_to='')),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('file_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='products.section')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='products.course'),
        ),
    ]
