# Generated by Django 4.0.1 on 2022-01-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
