# Generated by Django 4.0.1 on 2022-02-12 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_uploadfile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalproduct',
            name='variant',
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
