# Generated by Django 4.0.2 on 2022-05-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_imageupload_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='downloadable_file',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='redirect_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
