# Generated by Django 4.0.2 on 2022-05-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_downloadable_file_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='redirect_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
