# Generated by Django 4.0.1 on 2022-02-06 22:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_digital_product_physical_product_service_ticket_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='digital_product',
            new_name='DigitalProduct',
        ),
        migrations.RenameModel(
            old_name='physical_product',
            new_name='PhysicalProduct',
        ),
    ]
