# Generated by Django 4.0.2 on 2022-05-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_imageupload_image_alter_product_redirect_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
