# Generated by Django 4.0.1 on 2022-03-07 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_course_category_alter_digitalproduct_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='products.section'),
        ),
        migrations.AlterField(
            model_name='lessondetail',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_detail', to='products.lesson'),
        ),
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='products.course'),
        ),
    ]
