# Generated by Django 4.0.2 on 2022-05-20 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_imageupload_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_images', to='products.product')),
            ],
        ),
    ]
