# Generated by Django 4.0.1 on 2022-02-07 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_course_lesson_lessondetail_previewvideo_section_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='uploads',
            options={'verbose_name_plural': 'Uploads'},
        ),
        migrations.RemoveField(
            model_name='section',
            name='user',
        ),
    ]
