# Generated by Django 4.0.1 on 2022-02-07 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_category_options_alter_uploads_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lessondetail',
            name='user',
        ),
    ]
