# Generated by Django 4.0.2 on 2022-03-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_remove_previewvideo_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='content_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
