# Generated by Django 4.0.2 on 2022-03-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_content_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='content_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
