# Generated by Django 4.0.2 on 2022-03-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_content_url_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='content_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
