# Generated by Django 4.0.2 on 2022-03-21 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='auth_model',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='device_fingerprint',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='processor_response',
        ),
    ]
