# Generated by Django 4.0.2 on 2022-03-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_transaction_auth_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('digital', 'Digital Products'), ('tickets', 'Tickets'), ('services', 'Services')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
