# Generated by Django 4.0.2 on 2022-03-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_pricing_plan_id_and_more'),
        ('products', '0016_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pricing_tier',
            field=models.ManyToManyField(blank=True, to='subscription.Pricing'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('digital', 'Digital Product'), ('ticket', 'Ticket'), ('service', 'Service'), ('subscription', 'Subscription')], max_length=15),
        ),
    ]
