# Generated by Django 4.0.2 on 2022-03-21 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_course_pricing_tier_alter_product_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='pricing_tier',
        ),
    ]
