# Generated by Django 4.0.2 on 2022-03-28 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_course_pricing_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.uploadfile'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='file_url',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='LessonDetail',
        ),
    ]
